### ISSUE TITLE
Update project dependencies

### ISSUE THREAD

**Issue by WebTiger89** [Beepiz/BleScanCoroutines#3]
Hi,
could you please update your project dependencies. Meanwhile coroutines are stable and not experimental anymore.

The scanner.scan() method returns `kotlinx.coroutines.experimental.channels.ReceiveChannel` but I can only import `kotlinx.coroutines.channels.ReceiveChannel`

Thanks in advance!

**Comment by LouisCAD** [comment]
Hi, I'll work on an update for this. Sorry for the late response.

**Comment by LouisCAD** [comment]
Updated! Hope it works well on your side.
